In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# NumPy

In [3]:
# hiệu quả cho các mảng lớn dữ liệu
# sử dụng ít memory hơn built-in Python sequences
# rất nhanh

In [4]:
import numpy as np

In [5]:
arr1 = np.arange(1000000)

In [6]:
list1 = list(range(1000000))

In [29]:
%time for _ in range(15) : arr2 = arr1 * 2

CPU times: user 42.3 ms, sys: 507 µs, total: 42.9 ms
Wall time: 40.9 ms


In [30]:
%time for _ in range(15): list2 = [x*2 for x in list1]

CPU times: user 623 ms, sys: 82.7 ms, total: 705 ms
Wall time: 704 ms


## NumPy ndarray

In [32]:
# nhanh và linh hoạt
# ndarray - N-dimensional array object

In [33]:
import numpy as np

In [40]:
data = np.random.randn(3,2)

In [41]:
data

array([[ 1.21079042, -1.4879349 ],
       [-0.97577186, -0.25011196],
       [-0.90719796,  0.43691396]])

In [42]:
data * 100

array([[ 121.07904242, -148.79348977],
       [ -97.57718608,  -25.01119598],
       [ -90.71979589,   43.69139571]])

In [43]:
data + data

array([[ 2.42158085, -2.9758698 ],
       [-1.95154372, -0.50022392],
       [-1.81439592,  0.87382791]])

In [44]:
data.shape

(3, 2)

In [45]:
data.dtype

dtype('float64')

In [48]:
data.ndim

2

## Tạo ndarrays

In [49]:
d1 = [1,1.5,2,3,4]

In [50]:
arr1 = np.array(d1) 

In [51]:
arr1

array([1. , 1.5, 2. , 3. , 4. ])

In [59]:
arr1.dtype

dtype('float64')

In [52]:
d2 = [[1,5,6,7],[2,4,3,5]]

In [53]:
arr2 = np.array(d2)

In [54]:
arr2

array([[1, 5, 6, 7],
       [2, 4, 3, 5]])

In [55]:
arr2.dtype

dtype('int64')

In [56]:
arr2.ndim

2

In [57]:
arr2.shape

(2, 4)

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [67]:
np.empty((2,1,2))

array([[[1., 1.]],

       [[1., 1.]]])

In [69]:
arr1
np.zeros_like(arr1)

array([1. , 1.5, 2. , 3. , 4. ])

array([0., 0., 0., 0., 0.])

In [71]:
np.full((2,3),3)

array([[3, 3, 3],
       [3, 3, 3]])

In [72]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [75]:
arr1.dtype

dtype('float64')

In [76]:
arr2.dtype

dtype('int32')

## cast với astype method


In [107]:
# create a new array from arr2
arr3 = arr2.astype(np.float64)
arr3.dtype

dtype('float64')

In [108]:
arr3

array([1., 2., 3.])

In [109]:
arr4 = np.array([2.1,1.2,3])

In [110]:
arr4.dtype

dtype('float64')

In [111]:
arr4 = arr4.astype(np.int32)
arr4

array([2, 1, 3], dtype=int32)

In [112]:
arr5 = np.array(['1.21','2.3','3.4'],dtype=np.string_)

In [113]:
arr5.dtype

dtype('S4')

In [114]:
arr6 = arr5.astype(np.float64)
arr6

array([1.21, 2.3 , 3.4 ])

In [115]:
arr6.astype(arr4.dtype)

array([1, 2, 3], dtype=int32)

## Tính toán với ndarray

In [116]:
arr = np.array([[1,3,2],[2,3,4]])

In [117]:
arr

array([[1, 3, 2],
       [2, 3, 4]])

In [118]:
arr * arr

array([[ 1,  9,  4],
       [ 4,  9, 16]])

In [120]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [122]:
arr
1/arr

array([[1, 3, 2],
       [2, 3, 4]])

array([[1.        , 0.33333333, 0.5       ],
       [0.5       , 0.33333333, 0.25      ]])

In [123]:
arr ** 0.5

array([[1.        , 1.73205081, 1.41421356],
       [1.41421356, 1.73205081, 2.        ]])

In [130]:
arr * 2

array([[2, 6, 4],
       [4, 6, 8]])

In [124]:
arr2 = np.array([[2,5,2],[1,4,8]])

In [125]:
arr2

array([[2, 5, 2],
       [1, 4, 8]])

In [127]:
arr
arr2 > arr

array([[1, 3, 2],
       [2, 3, 4]])

array([[ True,  True, False],
       [False,  True,  True]])

## Indexing và slicing

In [137]:
arr = np.arange(5)

In [138]:
arr

array([0, 1, 2, 3, 4])

In [139]:
arr[2]

2

In [140]:
arr[1:3]

array([1, 2])

In [141]:
arr[1:3] = 5

In [142]:
arr

array([0, 5, 5, 3, 4])

In [143]:
## không giống list, np array slices chỉ là views của array gốc
## sửa đổi sẽ làm thay đổi array gốc

In [144]:
slice = arr[1:4]

In [145]:
slice

array([5, 5, 3])

In [146]:
slice[2] = 10

In [147]:
arr

array([ 0,  5,  5, 10,  4])

In [148]:
arr[:] = 3  # [:] gán cho tất cả

In [149]:
arr

array([3, 3, 3, 3, 3])

In [155]:
slice[:] = 4  # gán cho tất cả phần tử của slice 

In [156]:
arr

array([3, 4, 4, 4, 3])

In [157]:
a  = arr[1:4].copy()

In [161]:
a[1] = 5
a

array([4, 5, 4])

In [162]:
arr

array([3, 4, 4, 4, 3])

In [208]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [209]:
arr2[1]

array([4, 5, 6])

In [210]:
arr2[1][1]

5

In [211]:
arr2[1,1]

5

In [212]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [213]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [214]:
arr3d[0]

array([[1, 2],
       [3, 4]])

In [215]:
stored_vals = arr3d[0].copy()

In [216]:
arr3d[0] = 12

In [217]:
arr3d

array([[[12, 12],
        [12, 12]],

       [[ 5,  6],
        [ 7,  8]]])

In [218]:
arr3d[0] = stored_vals

In [219]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [220]:
arr3d[1,0]

array([5, 6])

In [221]:
# note again: ở đây tất cả trả về là views

In [222]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [223]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [224]:
arr2[:1]

array([[1, 2, 3]])

In [225]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [226]:
arr2[1,:2]

array([4, 5])

In [227]:
arr2[1:,2]

array([6])

In [228]:
arr2
arr2[:,1:]

array([[1, 2, 3],
       [4, 5, 6]])

array([[2, 3],
       [5, 6]])

In [229]:
arr2[:,1:] = 10

In [230]:
arr2

array([[ 1, 10, 10],
       [ 4, 10, 10]])